### ISSUE TITLE
GCC build error and MSVC warning on invalid cast of an rvalue

### ISSUE THREAD

**Issue by egorodet** [redorav/hlslpp#48]
Latest version of HLSL++ doest not build with GCC & MSVC at maximum warning level:
- [GCC errors example](https://egorodet.visualstudio.com/MethaneKit/_build/results?buildId=1258&view=logs&j=1287b841-589e-5c11-50b2-be5413241f28&t=d733a97e-f208-5206-76d9-21f22078e132): `hlsl++_sse.h:792:41: error: invalid cast of an rvalue expression of type ‘__m128’ {aka ‘__vector(4) float’} to type ‘const n128i&’ {aka ‘const __vector(2) long long int&’}   792 |  x = (const n128i&)_mm_load_ss((float*)p);`
- [MSVC warnings example](https://egorodet.visualstudio.com/MethaneKit/_build/results?buildId=1258&view=logs&j=b9e62f99-1a98-5ed7-01d2-f4794231ed79&t=31998140-03ba-501c-21d2-e5e191493112): `hlsl++_sse.h(792,20): warning C4238: nonstandard extension used: class rvalue used as lvalue`

**Comment by redorav** [comment]
You're right, I'm a bit confused as to why the CI says the build completed succesfully when clearly it's full of errors. I'll fix it this evening right after work.

**Comment by redorav** [comment]
Just for reference, here's the build where it's clearly broken. https://ci.appveyor.com/project/redorav/hlslpp/build/job/n435avvya2hpw8d9

It's probably a simple fix to reinterpret cast the pointer instead of casting to a const&

**Comment by redorav** [comment]
Apple Clang build is also broken but reporting successfully :( thanks for your reports @egorodet they're invaluable in some of these fixing some of these glaring oversights

**Comment by redorav** [comment]
The solution was actually a lot simpler than I was thinking. I also found a way for Linux and Apple builds to correctly report failures in AppVeyor. Let me know if there are any more issues. Fixed via 2eb2727e05ba15ec82d8c01882a713fcb3c562e1 and 908389bab54d9206c4905391db91fc40c7c85192
