### ISSUE TITLE
Better inclusion manual for usage in existing project

### ISSUE THREAD

**Issue by xXPancakeXx** [redorav/hlslpp#55]
It would be nice if it would contain a manual on how to incorporate it into an existing VisualStudio solution to be able to quickly use this awesome library. For example which settings have to be checked for a successful compilation or what else to pay attention to, because simple including the headers doesn't work.

I think that would be great, because it enables inexperienced c++, vs pipeline users to quickly try and use this awesome library.

**Comment by redorav** [comment]
Hi @xXPancakeXx, thanks for the feedback. What steps would you suggest for the integration? Where did it go wrong for you and how did you fix it? One thing I can think of now that you're telling me is that you need to add hlsl++ to your include paths, which I can definitely add to the instructions. Feel free to make as many suggestions as you want and we can make it work :)

**Comment by xXPancakeXx** [comment]
What I did, that didn't work: 
- Generated the workspace project with include generator. 
- Then took the VS Project and included it into my already existing solution and added the include-path to the project in the settings under C/C++ additional include dirs. 
- Now when I want to use e.g. a float3 it errors on compilation, for all files saying basically nothing was found.

When opening the generated version on its own everything works fine. Maybe I am missing something in VS that needs to be configured as well, which I don't know. So any further help would be very appreciated :)

**Comment by redorav** [comment]
Hi @xXPancakeXx did you try using float3 directly? Hlsl++ uses the hlslpp namespace, so I would try:

- hlslpp::float3 or
- using namespace hlslpp; and then use it as is presented in the samples

Let me know if that solves your issue

**Comment by xXPancakeXx** [comment]
I tried both ways. None worked. 

It must be some compiler settings in VS. Can you please elaborate on the steps you take especially in VS when adding the library to an existing project?

**Comment by redorav** [comment]
To be honest is should just be a question of adding the path to the includes. Here's an example

![image](https://user-images.githubusercontent.com/700032/151798427-7eff2e6b-c926-4a88-84c2-a1a58d34cc54.png)

**Comment by xXPancakeXx** [comment]
Thats the same thing I did, and it doesn't work for me. 
What is your exact folder structure? Where is your hlslcpp located?

**Comment by redorav** [comment]
I don't know if this is relevant but the project is **hlslpp** and not **hlslcpp**, just looking out for that in case it's a typo that's giving you problems.

Disregarding that, in your project Runner there is a file called Runner.cpp and I'm assuming you're including hlsl++.h from there. Then in your Project Runner you should right click, properties and follow the screenshot I sent earlier. You need to tell the Runner project that you want it to look for includes there. Bear in mind you don't even need to include the files like you have them in your screenshot.

**Comment by xXPancakeXx** [comment]
I did use the right, only made a typo in GitHub

The problem is that this is exactly what I did. 

![image](https://user-images.githubusercontent.com/22404008/151806310-6c611e26-1465-4a08-a926-cc5c0f7772d9.png)
Also tried it with an absolute path
![image](https://user-images.githubusercontent.com/22404008/151807058-03a6baa8-373e-433b-9c4f-dc30cf9b7785.png)

And tried it with nothing in there. Always the same errors.
Thats very strange and I am currently running out of ideas about where the problem is.
By the way, I really appreciate you taking the time to address this issue

**Comment by redorav** [comment]
Can you post here the errors that you're getting?

**Comment by xXPancakeXx** [comment]
Yes, I am compiling it in Release mode.

Of course:
1>D:\Bsc\SparseVoxelDAGs\NativePluginSource\hlslpp-3.1\include\hlsl++_vector_float.h(1329,23): error C2059: syntax error: 'const'
1>D:\Bsc\SparseVoxelDAGs\NativePluginSource\hlslpp-3.1\include\hlsl++_vector_float.h(1329,23): error C2059: syntax error: ')'
1>D:\Bsc\SparseVoxelDAGs\NativePluginSource\hlslpp-3.1\include\hlsl++_vector_float.h(1329,63): error C2143: syntax error: missing ';' before '{'
1>D:\Bsc\SparseVoxelDAGs\NativePluginSource\hlslpp-3.1\include\hlsl++_vector_float.h(1329,63): error C2447: '{': missing function header (old-style formal list?)
1>D:\Bsc\SparseVoxelDAGs\NativePluginSource\hlslpp-3.1\include\hlsl++_vector_float.h(1330,23): error C2059: syntax error: 'const'
1>D:\Bsc\SparseVoxelDAGs\NativePluginSource\hlslpp-3.1\include\hlsl++_vector_float.h(1330,23): error C2059: syntax error: ')'
1>D:\Bsc\SparseVoxelDAGs\NativePluginSource\hlslpp-3.1\include\hlsl++_vector_float.h(1330,63): error C2143: syntax error: missing ';' before '{'
1>D:\Bsc\SparseVoxelDAGs\NativePluginSource\hlslpp-3.1\include\hlsl++_vector_float.h(1330,63): error C2447: '{': missing function header (old-style formal list?)
1>D:\Bsc\SparseVoxelDAGs\NativePluginSource\hlslpp-3.1\include\hlsl++_vector_float.h(1331,23): error C2059: syntax error: 'const'
1>D:\Bsc\SparseVoxelDAGs\NativePluginSource\hlslpp-3.1\include\hlsl++_vector_float.h(1331,23): error C2059: syntax error: ')'
1>D:\Bsc\SparseVoxelDAGs\NativePluginSource\hlslpp-3.1\include\hlsl++_vector_float.h(1331,63): error C2143: syntax error: missing ';' before '{'
1>D:\Bsc\SparseVoxelDAGs\NativePluginSource\hlslpp-3.1\include\hlsl++_vector_float.h(1331,63): error C2447: '{': missing function header (old-style formal list?)
1>D:\Bsc\SparseVoxelDAGs\NativePluginSource\hlslpp-3.1\include\hlsl++_vector_float.h(1332,23): error C2059: syntax error: 'const'
1>D:\Bsc\SparseVoxelDAGs\NativePluginSource\hlslpp-3.1\include\hlsl++_vector_float.h(1332,23): error C2059: syntax error: ')'
1>D:\Bsc\SparseVoxelDAGs\NativePluginSource\hlslpp-3.1\include\hlsl++_vector_float.h(1332,63): error C2143: syntax error: missing ';' before '{'
1>D:\Bsc\SparseVoxelDAGs\NativePluginSource\hlslpp-3.1\include\hlsl++_vector_float.h(1332,63): error C2447: '{': missing function header (old-style formal list?)
1>D:\Bsc\SparseVoxelDAGs\NativePluginSource\hlslpp-3.1\include\hlsl++_vector_float.h(1339,23): error C2059: syntax error: 'const'
1>D:\Bsc\SparseVoxelDAGs\NativePluginSource\hlslpp-3.1\include\hlsl++_vector_float.h(1339,23): error C2059: syntax error: ')'
1>D:\Bsc\SparseVoxelDAGs\NativePluginSource\hlslpp-3.1\include\hlsl++_vector_float.h(1339,63): error C2143: syntax error: missing ';' before '{'
1>D:\Bsc\SparseVoxelDAGs\NativePluginSource\hlslpp-3.1\include\hlsl++_vector_float.h(1339,63): error C2447: '{': missing function header (old-style formal list?)
1>D:\Bsc\SparseVoxelDAGs\NativePluginSource\hlslpp-3.1\include\hlsl++_vector_float.h(1340,23): error C2059: syntax error: 'const'
1>D:\Bsc\SparseVoxelDAGs\NativePluginSource\hlslpp-3.1\include\hlsl++_vector_float.h(1340,23): error C2059: syntax error: ')'
1>D:\Bsc\SparseVoxelDAGs\NativePluginSource\hlslpp-3.1\include\hlsl++_vector_float.h(1340,63): error C2143: syntax error: missing ';' before '{'
1>D:\Bsc\SparseVoxelDAGs\NativePluginSource\hlslpp-3.1\include\hlsl++_vector_float.h(1340,63): error C2447: '{': missing function header (old-style formal list?)
1>D:\Bsc\SparseVoxelDAGs\NativePluginSource\hlslpp-3.1\include\hlsl++_vector_float.h(1341,23): error C2059: syntax error: 'const'
1>D:\Bsc\SparseVoxelDAGs\NativePluginSource\hlslpp-3.1\include\hlsl++_vector_float.h(1341,23): error C2059: syntax error: ')'
1>D:\Bsc\SparseVoxelDAGs\NativePluginSource\hlslpp-3.1\include\hlsl++_vector_float.h(1341,63): error C2143: syntax error: missing ';' before '{'
1>D:\Bsc\SparseVoxelDAGs\NativePluginSource\hlslpp-3.1\include\hlsl++_vector_float.h(1341,63): error C2447: '{': missing function header (old-style formal list?)
1>D:\Bsc\SparseVoxelDAGs\NativePluginSource\hlslpp-3.1\include\hlsl++_vector_float.h(1342,23): error C2059: syntax error: 'const'
1>D:\Bsc\SparseVoxelDAGs\NativePluginSource\hlslpp-3.1\include\hlsl++_vector_float.h(1342,23): error C2059: syntax error: ')'
1>D:\Bsc\SparseVoxelDAGs\NativePluginSource\hlslpp-3.1\include\hlsl++_vector_float.h(1342,63): error C2143: syntax error: missing ';' before '{'
1>D:\Bsc\SparseVoxelDAGs\NativePluginSource\hlslpp-3.1\include\hlsl++_vector_float.h(1342,63): error C2447: '{': missing function header (old-style formal list?)
1>D:\Bsc\SparseVoxelDAGs\NativePluginSource\hlslpp-3.1\include\hlsl++_vector_float.h(1479,25): error C2988: unrecognizable template declaration/definition
1>D:\Bsc\SparseVoxelDAGs\NativePluginSource\hlslpp-3.1\include\hlsl++_vector_float.h(1479,25): error C2059: syntax error: 'const'
1>D:\Bsc\SparseVoxelDAGs\NativePluginSource\hlslpp-3.1\include\hlsl++_vector_float.h(1479,46): error C2065: 'Y': undeclared identifier
1>D:\Bsc\SparseVoxelDAGs\NativePluginSource\hlslpp-3.1\include\hlsl++_vector_float.h(1479,25): error C2975: 'X': invalid template argument for 'hlslpp::swizzle1', expected compile-time constant expression
1>D:\Bsc\SparseVoxelDAGs\NativePluginSource\hlslpp-3.1\include\hlsl++_vector_float.h(548): message : see declaration of 'X'
1>D:\Bsc\SparseVoxelDAGs\NativePluginSource\hlslpp-3.1\include\hlsl++_vector_float.h(1479,25): error C2059: syntax error: ')'
1>D:\Bsc\SparseVoxelDAGs\NativePluginSource\hlslpp-3.1\include\hlsl++_vector_float.h(1479,94): error C2143: syntax error: missing ';' before '{'
1>D:\Bsc\SparseVoxelDAGs\NativePluginSource\hlslpp-3.1\include\hlsl++_vector_float.h(1479,94): error C2447: '{': missing function header (old-style formal list?)
1>D:\Bsc\SparseVoxelDAGs\NativePluginSource\hlslpp-3.1\include\hlsl++_vector_float.h(1480,18): error C2988: unrecognizable template declaration/definition
1>D:\Bsc\SparseVoxelDAGs\NativePluginSource\hlslpp-3.1\include\hlsl++_vector_float.h(1480,18): error C2059: syntax error: 'const'
1>D:\Bsc\SparseVoxelDAGs\NativePluginSource\hlslpp-3.1\include\hlsl++_vector_float.h(1480,39): error C2065: 'X': undeclared identifier
1>D:\Bsc\SparseVoxelDAGs\NativePluginSource\hlslpp-3.1\include\hlsl++_vector_float.h(1480,18): error C2975: 'X': invalid template argument for 'hlslpp::swizzle1', expected compile-time constant expression
1>D:\Bsc\SparseVoxelDAGs\NativePluginSource\hlslpp-3.1\include\hlsl++_vector_float.h(548): message : see declaration of 'X'
1>D:\Bsc\SparseVoxelDAGs\NativePluginSource\hlslpp-3.1\include\hlsl++_vector_float.h(1480,18): error C2059: syntax error: ')'
1>D:\Bsc\SparseVoxelDAGs\NativePluginSource\hlslpp-3.1\include\hlsl++_vector_float.h(1480,87): error C2143: syntax error: missing ';' before '{'
1>D:\Bsc\SparseVoxelDAGs\NativePluginSource\hlslpp-3.1\include\hlsl++_vector_float.h(1480,87): error C2447: '{': missing function header (old-style formal list?)
1>D:\Bsc\SparseVoxelDAGs\NativePluginSource\hlslpp-3.1\include\hlsl++_vector_float.h(1482,25): error C2988: unrecognizable template declaration/definition
1>D:\Bsc\SparseVoxelDAGs\NativePluginSource\hlslpp-3.1\include\hlsl++_vector_float.h(1482,25): error C2059: syntax error: 'const'
1>D:\Bsc\SparseVoxelDAGs\NativePluginSource\hlslpp-3.1\include\hlsl++_vector_float.h(1482,46): error C2065: 'Y': undeclared identifier
1>D:\Bsc\SparseVoxelDAGs\NativePluginSource\hlslpp-3.1\include\hlsl++_vector_float.h(1482,25): error C2975: 'X': invalid template argument for 'hlslpp::swizzle1', expected compile-time constant expression
1>D:\Bsc\SparseVoxelDAGs\NativePluginSource\hlslpp-3.1\include\hlsl++_vector_float.h(548): message : see declaration of 'X'
1>D:\Bsc\SparseVoxelDAGs\NativePluginSource\hlslpp-3.1\include\hlsl++_vector_float.h(1482,25): error C2059: syntax error: ')'
1>D:\Bsc\SparseVoxelDAGs\NativePluginSource\hlslpp-3.1\include\hlsl++_vector_float.h(1482,94): error C2143: syntax error: missing ';' before '{'
1>D:\Bsc\SparseVoxelDAGs\NativePluginSource\hlslpp-3.1\include\hlsl++_vector_float.h(1482,94): error C2447: '{': missing function header (old-style formal list?)
1>D:\Bsc\SparseVoxelDAGs\NativePluginSource\hlslpp-3.1\include\hlsl++_vector_float.h(1483,18): error C2988: unrecognizable template declaration/definition
1>D:\Bsc\SparseVoxelDAGs\NativePluginSource\hlslpp-3.1\include\hlsl++_vector_float.h(1483,18): error C2059: syntax error: 'const'
1>D:\Bsc\SparseVoxelDAGs\NativePluginSource\hlslpp-3.1\include\hlsl++_vector_float.h(1483,39): error C2065: 'X': undeclared identifier
1>D:\Bsc\SparseVoxelDAGs\NativePluginSource\hlslpp-3.1\include\hlsl++_vector_float.h(1483,18): error C2975: 'X': invalid template argument for 'hlslpp::swizzle1', expected compile-time constant expression
1>D:\Bsc\SparseVoxelDAGs\NativePluginSource\hlslpp-3.1\include\hlsl++_vector_float.h(548): message : see declaration of 'X'
1>D:\Bsc\SparseVoxelDAGs\NativePluginSource\hlslpp-3.1\include\hlsl++_vector_float.h(1483,18): error C2059: syntax error: ')'
1>D:\Bsc\SparseVoxelDAGs\NativePluginSource\hlslpp-3.1\include\hlsl++_vector_float.h(1483,87): error C2143: syntax error: missing ';' before '{'
1>D:\Bsc\SparseVoxelDAGs\NativePluginSource\hlslpp-3.1\include\hlsl++_vector_float.h(1483,87): error C2447: '{': missing function header (old-style formal list?)
1>D:\Bsc\SparseVoxelDAGs\NativePluginSource\hlslpp-3.1\include\hlsl++_vector_int.h(750,21): error C2059: syntax error: 'const'
1>D:\Bsc\SparseVoxelDAGs\NativePluginSource\hlslpp-3.1\include\hlsl++_vector_int.h(750,21): error C2059: syntax error: ')'
1>D:\Bsc\SparseVoxelDAGs\NativePluginSource\hlslpp-3.1\include\hlsl++_vector_int.h(750,57): error C2143: syntax error: missing ';' before '{'
1>D:\Bsc\SparseVoxelDAGs\NativePluginSource\hlslpp-3.1\include\hlsl++_vector_int.h(750,57): error C2447: '{': missing function header (old-style formal list?)
1>D:\Bsc\SparseVoxelDAGs\NativePluginSource\hlslpp-3.1\include\hlsl++_vector_int.h(751,21): error C2059: syntax error: 'const'
1>D:\Bsc\SparseVoxelDAGs\NativePluginSource\hlslpp-3.1\include\hlsl++_vector_int.h(751,21): error C2059: syntax error: ')'
1>D:\Bsc\SparseVoxelDAGs\NativePluginSource\hlslpp-3.1\include\hlsl++_vector_int.h(751,57): error C2143: syntax error: missing ';' before '{'
1>D:\Bsc\SparseVoxelDAGs\NativePluginSource\hlslpp-3.1\include\hlsl++_vector_int.h(751,57): error C2447: '{': missing function header (old-style formal list?)
1>D:\Bsc\SparseVoxelDAGs\NativePluginSource\hlslpp-3.1\include\hlsl++_vector_int.h(752,21): error C2059: syntax error: 'const'
1>D:\Bsc\SparseVoxelDAGs\NativePluginSource\hlslpp-3.1\include\hlsl++_vector_int.h(752,21): error C2059: syntax error: ')'
1>D:\Bsc\SparseVoxelDAGs\NativePluginSource\hlslpp-3.1\include\hlsl++_vector_int.h(752,57): error C2143: syntax error: missing ';' before '{'
1>D:\Bsc\SparseVoxelDAGs\NativePluginSource\hlslpp-3.1\include\hlsl++_vector_int.h(752,57): error C2447: '{': missing function header (old-style formal list?)
1>D:\Bsc\SparseVoxelDAGs\NativePluginSource\hlslpp-3.1\include\hlsl++_vector_int.h(753,21): error C2059: syntax error: 'const'
1>D:\Bsc\SparseVoxelDAGs\NativePluginSource\hlslpp-3.1\include\hlsl++_vector_int.h(753,21): error C2059: syntax error: ')'
1>D:\Bsc\SparseVoxelDAGs\NativePluginSource\hlslpp-3.1\include\hlsl++_vector_int.h(753,57): error C2143: syntax error: missing ';' before '{'
1>D:\Bsc\SparseVoxelDAGs\NativePluginSource\hlslpp-3.1\include\hlsl++_vector_int.h(753,57): error C2447: '{': missing function header (old-style formal list?)
1>D:\Bsc\SparseVoxelDAGs\NativePluginSource\hlslpp-3.1\include\hlsl++_vector_int.h(760,21): error C2059: syntax error: 'const'
1>D:\Bsc\SparseVoxelDAGs\NativePluginSource\hlslpp-3.1\include\hlsl++_vector_int.h(760,21): error C2059: syntax error: ')'
1>D:\Bsc\SparseVoxelDAGs\NativePluginSource\hlslpp-3.1\include\hlsl++_vector_int.h(760,57): error C2143: syntax error: missing ';' before '{'
1>D:\Bsc\SparseVoxelDAGs\NativePluginSource\hlslpp-3.1\include\hlsl++_vector_int.h(760,57): error C2447: '{': missing function header (old-style formal list?)
1>D:\Bsc\SparseVoxelDAGs\NativePluginSource\hlslpp-3.1\include\hlsl++_vector_int.h(761,21): error C2059: syntax error: 'const'
1>D:\Bsc\SparseVoxelDAGs\NativePluginSource\hlslpp-3.1\include\hlsl++_vector_int.h(761,21): error C2059: syntax error: ')'
1>D:\Bsc\SparseVoxelDAGs\NativePluginSource\hlslpp-3.1\include\hlsl++_vector_int.h(761,57): error C2143: syntax error: missing ';' before '{'
1>D:\Bsc\SparseVoxelDAGs\NativePluginSource\hlslpp-3.1\include\hlsl++_vector_int.h(761,57): error C2447: '{': missing function header (old-style formal list?)
1>D:\Bsc\SparseVoxelDAGs\NativePluginSource\hlslpp-3.1\include\hlsl++_vector_int.h(762,21): error C2059: syntax error: 'const'
1>D:\Bsc\SparseVoxelDAGs\NativePluginSource\hlslpp-3.1\include\hlsl++_vector_int.h(762,21): error C2059: syntax error: ')'
1>D:\Bsc\SparseVoxelDAGs\NativePluginSource\hlslpp-3.1\include\hlsl++_vector_int.h(762,57): error C2143: syntax error: missing ';' before '{'
1>D:\Bsc\SparseVoxelDAGs\NativePluginSource\hlslpp-3.1\include\hlsl++_vector_int.h(762,57): error C2447: '{': missing function header (old-style formal list?)
1>D:\Bsc\SparseVoxelDAGs\NativePluginSource\hlslpp-3.1\include\hlsl++_vector_int.h(763,21): error C2059: syntax error: 'const'
1>D:\Bsc\SparseVoxelDAGs\NativePluginSource\hlslpp-3.1\include\hlsl++_vector_int.h(763,21): error C2059: syntax error: ')'
1>D:\Bsc\SparseVoxelDAGs\NativePluginSource\hlslpp-3.1\include\hlsl++_vector_int.h(763,57): error C2143: syntax error: missing ';' before '{'
1>D:\Bsc\SparseVoxelDAGs\NativePluginSource\hlslpp-3.1\include\hlsl++_vector_int.h(763,57): error C2447: '{': missing function header (old-style formal list?)
1>D:\Bsc\SparseVoxelDAGs\NativePluginSource\hlslpp-3.1\include\hlsl++_vector_uint.h(750,22): error C2059: syntax error: 'const'
1>D:\Bsc\SparseVoxelDAGs\NativePluginSource\hlslpp-3.1\include\hlsl++_vector_uint.h(750,22): error C2059: syntax error: ')'
1>D:\Bsc\SparseVoxelDAGs\NativePluginSource\hlslpp-3.1\include\hlsl++_vector_uint.h(750,60): error C2143: syntax error: missing ';' before '{'
1>D:\Bsc\SparseVoxelDAGs\NativePluginSource\hlslpp-3.1\include\hlsl++_vector_uint.h(750,60): error C2447: '{': missing function header (old-style formal list?)
1>D:\Bsc\SparseVoxelDAGs\NativePluginSource\hlslpp-3.1\include\hlsl++_vector_uint.h(751,22): error C2059: syntax error: 'const'
1>D:\Bsc\SparseVoxelDAGs\NativePluginSource\hlslpp-3.1\include\hlsl++_vector_uint.h(751,22): error C2059: syntax error: ')'
1>D:\Bsc\SparseVoxelDAGs\NativePluginSource\hlslpp-3.1\include\hlsl++_vector_uint.h(751,60): error C2143: syntax error: missing ';' before '{'
1>D:\Bsc\SparseVoxelDAGs\NativePluginSource\hlslpp-3.1\include\hlsl++_vector_uint.h(751,60): error C2447: '{': missing function header (old-style formal list?)
1>D:\Bsc\SparseVoxelDAGs\NativePluginSource\hlslpp-3.1\include\hlsl++_vector_uint.h(752,22): error C2059: syntax error: 'const'
1>D:\Bsc\SparseVoxelDAGs\NativePluginSource\hlslpp-3.1\include\hlsl++_vector_uint.h(752,22): fatal error C1003: error count exceeds 100; stopping compilation

**Comment by redorav** [comment]
Ok I see the issue. It's choking on the function min and max. I wonder, do you have them defined or are you including windows.h in the same file? Windows has this silly legacy thing where they define min and max and basically will break the library. What you need to do is put #undef min and #undef max after you include the windows header.

**Comment by xXPancakeXx** [comment]
I never explicitly included windows.h anywhere and neither defined it myself, but I am using min and max in my code. It seems to be a macro of some sort and it is defined in minwindef.h in another library which probably uses windows.h.

I have now provided an undef for both before the inclusion of hlsl++.h and it compiles now. Amazing :). This should probably go into the installation side nodes, because it seems pretty common that you include windows.h and the received error message from the compiler isn't really useful. At least for me it wasn't. :)

**Comment by redorav** [comment]
That is true, I'll make a note of it. Unfortunately there's not a lot else I can do from my side, tbh Windows should get rid of all their silly macros but that's not going to happen :)

I'm glad I could be of help.

**Comment by xXPancakeXx** [comment]
Wouldnt it be possible to just add the #undef in your hlsl++.h at the beginning, and to just make sure that hlsl++.h is included after all libraries which require these macros? Anyways I guess it's fine as long as you mention it somewhere.

**Comment by redorav** [comment]
I hear you, but this is broken for things like std::min and std::max as well, I'd rather not introduce behavior that could confuse someone even more (std::min and std::max work but only when including hlsl++ or something like that). I've added a mention in the landing page. Ultimately, I think the correct and consistent solution is to force windows to not declare those macros, globally for the project, using NOMINMAX.
