### ISSUE TITLE
Cast between types

### ISSUE THREAD

**Issue by plekakis** [redorav/hlslpp#57]
Currently there is no way to cast between different types. For example, it is very useful in HLSL to take the 3x3 top-left part of a 4x4 matrix:
`float3x3 m1 = (float3x3)m0;`

It would be nice to have a similar way to do such operations, either by a user defined conversion function or even additional constructors.

**Comment by redorav** [comment]
Hi Akis, that is definitely a good idea and simple to implement too. Downcasting is probably faster than upcasting as we don't need to ensure contents (e.g. from 3x3 to 4x4 we probably want to set (0,0,0,1) for the last column)

Same comment applies as the last report, I'll definitely come to it as soon as I can but you're welcome to implement locally and replace with my implementation when I get to it.

**Comment by plekakis** [comment]
That seems fine, thank you very much!

**Comment by redorav** [comment]
Excellent, closing now :) Anything else let me know
