### ISSUE TITLE
Integer vector division is working incorrectly on Macs with Apple M1 (ARM)

### ISSUE THREAD

**Issue by egorodet** [redorav/hlslpp#60]
Signed and unsigned integer vector division operators both for scalar and vector divisors are working incorrectly when compiled for Apple M1 on MacOS >= 11. Here's an example of failed Catch tests for a wrapper class [Point<T,size>](https://github.com/egorodet/MethaneKit/blob/develop/Modules/Data/Types/Include/Methane/Data/Point.hpp) in my project for HLSL++ vector. It is also reproducible under PR #59 , which adds missing unit tests for division operator.
<img width="1081" alt="Screenshot 2022-07-18 at 12 21 25" src="https://user-images.githubusercontent.com/21955635/179481954-7df0ac7e-d184-43bc-b516-1d4627c5160c.png">

**Comment by redorav** [comment]
Hi @egorodet, it is a known issue that integer division is broken. There are no intrinsics for integer division and when I sat down to find a solution I couldn't find anything that wasn't a bit of a monster and left it for the future. Currently all it does is cast to float, divide and cast back which obviously isn't very good.

I had an issue open already, I'll close that one and track here instead. If you know of a good solution I could put in that would make it much easier, otherwise I'll see when I can find a bit of time to look into it.

**Comment by redorav** [comment]
Copying original comment from the other bug:

> SSE doesn't have native division instructions for vectors. One possibility is to extract the scalars, divide, then put back. Another alternative is to take a look at this website which seems to have alternatives and claim to be fast
> 
> http://libdivide.com/

**Comment by egorodet** [comment]
Hi @redorav, yes I see that current implementation is not perfect, but it seems to work in most cases on x86/64 architecture, but gives completely wrong results on ARM (Apple M1 in my case). So additionally to existing issue, there's something wrong in the NEON implementation of the current workaround.

**Comment by egorodet** [comment]
I added workaround in the code of my wrapper class `Point`, so it should not be a stopper for me. It's up to you if it's better to keep or close this issue. I'm fine with description of the existing issue, just want to raise its priority because current implementation could give wrong results.

**Comment by redorav** [comment]
I've fixed division in NEON, the explanation for why it was broken is here f8ebd874c8fdb5328c0c21e4b7fc8740e7b30540. Let me know if this is still an issue for you. It is "fixed" in the sense that it is consistent with SSE now, but the issue of large integers remains.

**Comment by egorodet** [comment]
@redorav Thanks for quick turnaround! My tests are passing fine with this update on M1 ✅

**Comment by redorav** [comment]
Thank you for detailed report, hlsl++ is a lot better thanks to your efforts
