### ISSUE TITLE
Improve HLSL++ unit tests by using full-featured testing framework

### ISSUE THREAD

**Issue by egorodet** [redorav/hlslpp#62]
Current approach to [unit testing in HLSL++](https://github.com/redorav/hlslpp/tree/master/src) has not enough flexibility to find regressions in Release builds and reporting them in CI build system. HLSL++ unit tests are checking test results with [assert](https://en.cppreference.com/w/cpp/error/assert) function which works only in Debug builds and is excluded from Release builds (where `NDEBUG` macro is defined), making it impossible to test CI build results. Also `assert` is limited to terminating program on first failure, without possibility to report all test failures, which makes it inconvenient to debug code.

I would suggest to use some full-featured unit testing framework like [Catch2](https://github.com/catchorg/Catch2), which is also header-only and can be used in form of a single header, but allows to implement tests with [much greater flexibility](https://github.com/catchorg/Catch2/blob/devel/docs/why-catch.md). For example, see templated unit tests in my project [PointTest.cpp](https://github.com/egorodet/MethaneKit/blob/develop/Tests/Data/Types/PointTest.cpp) for a wrapper class [Point<T,size>](https://github.com/egorodet/MethaneKit/blob/develop/Modules/Data/Types/Include/Methane/Data/Point.hpp) around HLSL++ vector, which is testing vector functions for all possible types and sizes of vectors. CI build system can be configured to [display test reports](https://egorodet.visualstudio.com/MethaneKit/_build/results?buildId=1809&view=ms.vss-test-web.build-test-results-tab) for regressions analysis.

**Comment by redorav** [comment]
This is something I've wanted to do for some time now (including performance tests) but haven't really got around to doing. I'll keep this bug open and see when I can get on it.

**Comment by redorav** [comment]
I think if you're happy with the way this works currently I can close it now. I made it more manual than perhaps you'd like but I had a bit of fun doing the appveyor integration and a little unit test framework that works well enough for the purposes of this.
