### ISSUE TITLE
Upgrade warnings to errors

### ISSUE THREAD

**Issue by redorav** [redorav/hlslpp#70]
This needs fixing all spurious warnings from the unit tests like unused variables, etc. It's straightforward but will be time-consuming

**Comment by redorav** [comment]
@egorodet Just thought you'd be interested to know that I have now promoted warnings to errors and fixed all of them so the build is now fully green across all the platforms I test

**Comment by egorodet** [comment]
@redorav Nice to hear it's fixed! Thank you!
