### ISSUE TITLE
round() on ARM Neon uses wrong rounding mode

### ISSUE THREAD

**Issue by mlangerak** [redorav/hlslpp#71]
For ARM Neon, `_hlslpp_round_ps` is implemented using `vrndq_f32` which rounds to zero instead of the expected round to even. Instead, `_hlslpp_round_ps` should use `vrndnq_f32`.

**Comment by redorav** [comment]
Hi @mlangerak thanks for your interest and reporting. I'll take a look as soon as I can this evening and fix it asap. Thanks!

**Comment by redorav** [comment]
Fixed via 86bae48c9c733d084fe6fd2c36b3a8d008a53640 and added unit tests
