### ISSUE TITLE
mul() intrinsic is missing some overloads.

### ISSUE THREAD

**Issue by mlangerak** [redorav/hlslpp#72]
The following `mul()` intrinsic overloads are not implemented (there may be more missing ones than these):

`float3 mul(float2 v, float2x3 m)`
`float4 mul(float3 v, float3x4 m)`
`float2 mul(float2x3 m, float3 v)`
`float3 mul(float3x4 m, float4 v)`

**Comment by redorav** [comment]
It seems like I added the overloads I needed for square matrices and forgot about the rest. Same as the other issue, I'll take a look and add those soon. Thanks!

**Comment by redorav** [comment]
@mlangerak All fixed now! Let me know if you need anything else.

Fixed via dfb2380871cc778ffc72c17517a5921e21112e4b
