### ISSUE TITLE
Missing matrix constructors

### ISSUE THREAD

**Issue by mlangerak** [redorav/hlslpp#75]
Some matrices are missing expected constructors. For example, float2x3 does not have a constructor taking 2 float3's as expected.

**Comment by redorav** [comment]
@mlangerak thanks for reporting, I'll take a look at this when I can

**Comment by redorav** [comment]
I've added the constructors you need in ea4790da0116952b1653cedbd3f28fb72e965131. Based on your other open issue this is unlikely to cover your needs but at least this bit of functionality is available now
