### ISSUE TITLE
internal::round_float gives incorrect results

### ISSUE THREAD

**Issue by mlangerak** [redorav/hlslpp#79]
`internal::round_float` gives incorrect results for certain arguments. E.g. `internal::round_float(0.9f)` will result in -1.

I would suggest changing the implementation to use `std::round()` for correctness. Alternatively, if the overhead of `std::round`'s checks for nan and inf is a concern, this:
`static_cast<int>(x + std::copysign(0.5f, x))`
will give identical results to std::lround essentially everywhere except for a few ulp in case x is very near +/- 0.5, since the addition in the expression is subject to destructive cancellation but it is so minor you can ignore it.

**Comment by redorav** [comment]
The issue was that std::round was not giving me the same results as hlsl for 0.5, but rounding 0.9 to -1 is definitely wrong, I'll take a look at that again, thanks for reporting

**Comment by redorav** [comment]
Can you try latest code?

**Comment by mlangerak** [comment]
That fixes my immediate issue, but I did not double check that the fixed code is correct for rounding negative numbers, does the unit test cover these cases? (In my particular case where I ran into this bug, negative numbers are clamped to zero after the rounding operation so any bugs in rounding negative numbers would not show up there.)

What are the differences between HLSL and std::round?

**Comment by redorav** [comment]
It's at x.5 that it goes wrong, not just with hlsl but with the simd intrinsics as well. 0.5 rounds to 1 with std::round but to 0 in the other cases.

The unit tests have negative numbers as well. However I may have to improve them because they clearly didn't catch the issue last time. I did do a few more tests locally.
