### ISSUE TITLE
vcpkg support?

### ISSUE THREAD

**Issue by plekakis** [redorav/hlslpp#83]
Not an issue per se, however is there a plan to add hlslpp to vcpkg?

**Comment by redorav** [comment]
Hi Pantelis, there's no plan to add to vcpkg but also no impediment on my part. Conan has packages for hlsl++ that I haven't added for example

**Comment by plekakis** [comment]
Thank you, I am just starting to use vcpkg and not sure if I should simply add a port to the registry or perhaps let you eventually do it? 
What is your preferred way?

**Comment by redorav** [comment]
I don't really know what needs doing in terms of adding it, I don't use vcpkg but if you have experience and need to add a file or recipe or something to this repository we can see how to integrate it

**Comment by plekakis** [comment]
I can do a test this afternoon, it doesn't seem very involved. Basically following:
https://learn.microsoft.com/en-us/vcpkg/get_started/get-started-packaging?pivots=shell-cmd

**Comment by plekakis** [comment]
I have make a new hlslpp port, tested it and did a PR for microsoft here:

https://github.com/microsoft/vcpkg/pull/40400

It all seems good and according to the vcpkg formatting & documentation.

**Comment by redorav** [comment]
Manu thanks! Quick question does it let you name things as hlsl++ or does it need the pp instead? I try to favor ++ even though github doesn't let me

**Comment by redorav** [comment]
Conan seems to have it the same way, maybe it doesn't really matter...

https://conan.io/center/recipes/hlslpp

**Comment by plekakis** [comment]
Oh dear, I didn't think to try that...
I've already submitted the PR, let me see if I can change it though.

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by plekakis** [comment]
We can leave it as hlslpp then, if that's alright.

**Comment by redorav** [comment]
Yesh that's fine, feel free to close :)

**Comment by plekakis** [comment]
Thank you, it's being merged to vcpkg now.
I plan on doing so whenever you make a new release, might need a way to monitor that :-)
