### ISSUE TITLE
float3x3 from 4x4 seems wrong

### ISSUE THREAD

**Issue by plekakis** [redorav/hlslpp#87]
Initialising a float3x3 (and possibly others, I haven't tested the whole range of matrices) from a float4x4 results in the wrong matrix.

`
float4x4 worldToView = ....
float3x3 worldToView2 = float3x3(worldToView);`

![{A9242802-BBF3-4DD1-BBDE-85A8D12B88F3}](https://github.com/user-attachments/assets/3be63e7e-da4a-40f9-81ee-7699e0f71737)

I am still debugging this, but there might be something wrong.

Also, is there a chance we can get implicit cast operators for better interopability with HLSL?

**Comment by redorav** [comment]
Hey Pantelis, I'm away for the weekend but can take a look when I'm back.

I can add implicit operators behind a define, I'm not a big fan of them and even in hlsl I enable that warning as an error. Let me know which ones would be useful.

As for the error I'm surprised, the code should be extremely simple, it might just be a typo.

**Comment by redorav** [comment]
@plekakis I was able to repro in AVX mode. Can you let me know which kind of implicit casts you want as well?

**Comment by redorav** [comment]
I'll close this and you can make a request for implicit casts in a different issue

**Comment by plekakis** [comment]
Thank you, I have submitted the new version to vcpkg today.
Let's ignore the casts for now.
